# Generated by Django 3.2.13 on 2022-06-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersubscriptions_postrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscriptions',
            name='postRequests',
        ),
    ]
